# Generated by Django 2.2 on 2019-04-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('regista', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
                ('prezzo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(max_length=100)),
                ('citta', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Noleggio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Film')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Utente')),
            ],
        ),
        migrations.CreateModel(
            name='GenereFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Film')),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Genere')),
            ],
        ),
        migrations.CreateModel(
            name='FilmAttori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Attori')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Film')),
            ],
        ),
    ]
